version: "3"

services:
  app:
    build:
      context: .
    env_file: .env
    container_name: api_tcc
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      NODE_VERSION: ${NODE_VERSION}
      YARN_VERSION: ${YARN_VERSION}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: db
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      APP_KEYS: ${APP_KEYS}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./app:/srv/app
    ports:
      - 1338:1338
    # depends_on:
    #   - db
    # networks:
    #   - strapi

  # db:
  #   image: postgres
  #   container_name: postgres
  #   env_file: .env
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: ${DATABASE_USERNAME}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #     POSTGRES_DB: ${DATABASE_PASSWORD}
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - strapi

volumes:
  strapi-data:

# networks:
#   strapi:
#     name: Strapi
#     driver: bridge