version: '4'

services:
  api_tcc:
    container_name: strapi
    build: .
    image: naskio/strapi
    environment:
      NODE_ENV: ${NODE_ENV}
      NODE_VERSION: ${NODE_VERSION}
      YARN_VERSION: ${YARN_VERSION}
      DATABASE_HOST: db
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      APP_KEYS: ${APP_KEYS}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 1338:1338
    volumes:
      - /home/api_tcc:/srv/app # Nesse caso, copie o projeto para /home/Strapi/
    depends_on:
      - db_tcc
    networks:
      - strapi

  db_tcc:
    container_name: postgres
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5433:5433
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge