version: '4'

services:
  api_tcc:
    container_name: api_tcc
    build: .
    env_file: .env
    image: naskio/strapi
    environment:
      NODE_ENV: ${NODE_ENV}
      NODE_VERSION: ${NODE_VERSION}
      YARN_VERSION: ${YARN_VERSION}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      APP_KEYS: ${APP_KEYS}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 1338:1338
    volumes:
      - /home/api_tcc:/srv/app # Nesse caso, copie o projeto para /home/Strapi/
      # - ./app:/srv/app
    depends_on:
      - db
    networks:
      - strapi

  db:
    container_name: postgres
    env_file: .env
    image: postgres
    volumes:
      # - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    networks:
      - strapi

volumes:
  api-tcc-data:

networks:
  strapi:
    name: Strapi
    driver: bridge